services:
  postgres:
    image: postgres:16
    container_name: mini-signify-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_signify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: mini-signify-backend-container
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: mini-signify-frontend-container
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  postgres_data: