encryptionsalt: v1:nuAcJnUCemw=:v1:UGG2J2OoyUpLftcV:o87iLGKOxPuQUlA2f7wlgOGXrOfT/w==
config:
  aws:region: ap-southeast-1
  mini-signify-infra:dbPassword:
    secure: v1:ixHmSRlrN0RDJV9/:P2LsUKS6JbRfVLtn+sJeJNZidWBAvOpFXFk=
  mini-signify-infra:backendImageTag: 86478fadea3cd29bf2d71551c7b2ce6cadd16982
